# Generated by Django 4.2.1 on 2023-05-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=35)),
                ("location", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField()),
                ("per_sqr_meters", models.PositiveIntegerField()),
                ("land_image", models.ImageField(upload_to="land_images")),
                ("layout_image", models.ImageField(upload_to="land_layout_images")),
            ],
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("review", models.TextField()),
                ("user_image", models.ImageField(upload_to="testimonail_users_images")),
            ],
        ),
    ]
