# Generated by Django 4.2.1 on 2023-05-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("services", "0002_testimonial_delete_testimonials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="land",
            name="layout_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="layout_image",
                to="wagtailimages.image",
            ),
        ),
    ]
