# Generated by Django 4.2.1 on 2023-05-22 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("blog", "0003_blogpagegalleryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.DeleteModel(
            name="BlogPageGalleryImage",
        ),
    ]
